### PR TITLE
Adding environment variables for constants from plasma-utils

### LINKED ISSUE #46: Environment variables for constants from `plasma-utils`
**Is your feature request related to a problem? Please describe.**
Right now, constants are hardcoded into the contract and have to be manually updated.  This is especially annoying since vyper doesn't allow you to declare a `foo: constant(uint256) = X` and then declare an array `bar: bytes[foo]`... it only accepts `bar: bytes[X]` as a numeric hardcoded literal.
 
**Describe the solution you'd like**
We store constants [here](https://github.com/plasma-group/plasma-utils/blob/master/src/constants.js) in plasma-utils already. We just need a pre-test loop on setup to directly modify the `.vy` files.  This would look like, in vyper, being able to declare `foo: bytes[${FOO_SIZE}]` which gets overwritten right before compilation.

**Describe alternatives you've considered**
The only thing I'm not sure about is, should it be the entire type, including the `bytes[]` part? So we just declare `foo: ${FOO_TYPE}` instead.

**Additional context**
See [this](https://github.com/plasma-group/plasma-utils/issues/25) issue in `plasma-utils`

### PR DESCRIPTION
**Pull request by nanspro**
Constants from **plasma-utils** are stored in .env file.
Running `Precompile.js` will inject env variables from **.env**  and hence it kind of precompiles all the contracts.
Fixes #46

### CODE REVIEW

**Comment by ben-chain** [comment]
Thank you, this looks like a great start! :)

I see that this was written in Python--do you think it would be possible to write directly in Javascript? Since the rest of the code is in js, including the `plasma-utils` library where the constants are, we should probably keep it consistent. Sorry, maybe I should've specified that up front!

**Comment by nanspro** [comment]
Yeah it makes more sense to have it in js but you should've specified that because I thought we were using virtualenv anyway to activate vyper and hence we can have dependency(dotenv) installed there.

**Comment by nanspro** [comment]
Converting to js won't be a problem.
I'll update it in 3-4hrs

**Comment by nanspro** [comment]
@ben-chain  please review!!

**Comment by ben-chain** [comment]
Hey Rahul, sorry for just seeing this--I must have missed the @ notification.

The next step here will be to pull the environment variables from `plasma-utils` js files, but for now, I think this is great for what is needed in #40!  I will merge, thanks so much! :)

**Pull request merged**
